USE master;
GO
ALTER DATABASE COMERCIO_DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE COMERCIO_DB;
GO

CREATE DATABASE COMERCIO_DB;
GO
USE COMERCIO_DB;
GO

IF OBJECT_ID('dbo.DETALLE_VENTA', 'U') IS NOT NULL DROP TABLE dbo.DETALLE_VENTA;
IF OBJECT_ID('dbo.VENTAS', 'U') IS NOT NULL DROP TABLE dbo.VENTAS;
IF OBJECT_ID('dbo.PRECIOS_COMPRA', 'U') IS NOT NULL DROP TABLE dbo.PRECIOS_COMPRA;
IF OBJECT_ID('dbo.CLIENTES', 'U') IS NOT NULL DROP TABLE dbo.CLIENTES;
IF OBJECT_ID('dbo.USUARIO_ROLES', 'U') IS NOT NULL DROP TABLE dbo.USUARIO_ROLES;
IF OBJECT_ID('dbo.ROLES', 'U') IS NOT NULL DROP TABLE dbo.ROLES;
IF OBJECT_ID('dbo.USUARIOS', 'U') IS NOT NULL DROP TABLE dbo.USUARIOS;
IF OBJECT_ID('dbo.PRODUCTO_PROVEEDOR', 'U') IS NOT NULL DROP TABLE dbo.PRODUCTO_PROVEEDOR;
IF OBJECT_ID('dbo.COMPRA_LINEAS', 'U') IS NOT NULL DROP TABLE dbo.COMPRA_LINEAS;
IF OBJECT_ID('dbo.COMPRAS', 'U') IS NOT NULL DROP TABLE dbo.COMPRAS;
IF OBJECT_ID('dbo.PRODUCTOS', 'U') IS NOT NULL DROP TABLE dbo.PRODUCTOS;
IF OBJECT_ID('dbo.PROVEEDORES', 'U') IS NOT NULL DROP TABLE dbo.PROVEEDORES;
IF OBJECT_ID('dbo.CATEGORIAS', 'U') IS NOT NULL DROP TABLE dbo.CATEGORIAS;
IF OBJECT_ID('dbo.MARCAS', 'U') IS NOT NULL DROP TABLE dbo.MARCAS;
GO


CREATE TABLE MARCAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Activo BIT NOT NULL DEFAULT(1)
);
GO

CREATE TABLE CATEGORIAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Activo BIT NOT NULL DEFAULT(1)
);
GO

CREATE TABLE PROVEEDORES (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NULL,
    RazonSocial VARCHAR(200) NOT NULL,
    Documento VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    Telefono VARCHAR(50) NULL,
    Direccion VARCHAR(200) NULL,
    Localidad VARCHAR(100) NULL,
    CondicionIVA VARCHAR(50) NULL,
    Activo BIT NOT NULL DEFAULT(1)
);
GO

CREATE TABLE PRODUCTOS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CodigoSKU VARCHAR(50) NULL,
    Descripcion VARCHAR(100) NOT NULL,
    IdMarca INT NULL,
    IdCategoria INT NOT NULL,
    StockMinimo DECIMAL(18, 2) NULL,
    StockActual DECIMAL(18, 2) NULL,
    PorcentajeGanancia DECIMAL(5, 2) NULL,
    Activo BIT NOT NULL DEFAULT(1),
    Habilitado BIT NOT NULL DEFAULT(1), 
    CONSTRAINT UQ_PRODUCTOS_CodigoSKU UNIQUE (CodigoSKU),
    CONSTRAINT FK_PRODUCTOS_MARCA FOREIGN KEY (IdMarca) REFERENCES MARCAS(Id),
    CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIAS(Id)
);
GO



CREATE TABLE PRECIOS_COMPRA (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdProducto INT NOT NULL,
    IdProveedor INT NULL,
    Precio MONEY NOT NULL,
    Fecha DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT FK_PRECIOS_COMPRA_PRODUCTO FOREIGN KEY (IdProducto) REFERENCES PRODUCTOS(Id),
    CONSTRAINT FK_PRECIOS_COMPRA_PROVEEDOR FOREIGN KEY (IdProveedor) REFERENCES PROVEEDORES(Id)
);
GO

CREATE TABLE USUARIOS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(50) NULL,
    Documento VARCHAR(20) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telefono VARCHAR(50) NULL,
    Direccion VARCHAR(200) NULL,
    Localidad VARCHAR(100) NULL,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Activo BIT NOT NULL DEFAULT(1)
);
GO

CREATE TABLE ROLES (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL
);
GO

INSERT INTO ROLES (Descripcion) VALUES ('Admin'), ('Vendedor');
GO

CREATE TABLE USUARIO_ROLES (
    IdUsuario INT NOT NULL,
    IdRol INT NOT NULL,
    PRIMARY KEY (IdUsuario, IdRol),
    CONSTRAINT FK_USUARIO_ROLES_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(Id),
    CONSTRAINT FK_USUARIO_ROLES_ROL FOREIGN KEY (IdRol) REFERENCES ROLES(Id)
);
GO

CREATE TABLE CLIENTES (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Documento VARCHAR(20) NULL, 
    Email VARCHAR(100) NULL,
    Telefono VARCHAR(50) NULL,
    Direccion VARCHAR(200) NULL,
    Localidad VARCHAR(100) NULL,
    CondicionIVA VARCHAR(50) NULL,
    Habilitado BIT NOT NULL DEFAULT(1),
    IdUsuarioAlta INT NOT NULL,

    FOREIGN KEY (IdUsuarioAlta) REFERENCES USUARIOS(Id)
);
GO

-- UNIQUE SOLO PARA CLIENTES ACTIVOS
CREATE UNIQUE INDEX UX_CLIENTES_Documento_Habilitado
ON CLIENTES (Documento)
WHERE Habilitado = 1;
GO



CREATE TABLE VENTAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdUsuario INT NOT NULL,
    IdCliente INT NOT NULL,
    Fecha DATETIME NOT NULL DEFAULT(GETDATE()),
    NumeroFactura VARCHAR(50) NULL,
    NumeroNC VARCHAR(50) NULL,           
    MetodoPago VARCHAR(50) NULL,
    Total DECIMAL(18,2) NOT NULL,

    Cancelada BIT NOT NULL DEFAULT(0),
    MotivoCancelacion VARCHAR(250) NULL,
    FechaCancelacion DATETIME NULL,
    IdUsuarioCancelacion INT NULL,

    CONSTRAINT FK_VENTAS_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(Id),
    CONSTRAINT FK_VENTAS_CLIENTE FOREIGN KEY (IdCliente) REFERENCES CLIENTES(Id),
    CONSTRAINT FK_VENTAS_USUARIO_CANCEL FOREIGN KEY (IdUsuarioCancelacion) REFERENCES USUARIOS(Id)
);
GO


CREATE TABLE DETALLE_VENTA (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdVenta INT NOT NULL,
    IdProducto INT NOT NULL,
    Cantidad DECIMAL(18,2) NOT NULL,
    PrecioUnitario DECIMAL(18,2) NOT NULL,

    CONSTRAINT FK_DETALLE_VENTA_VENTA FOREIGN KEY (IdVenta) REFERENCES VENTAS(Id),
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (IdProducto) REFERENCES PRODUCTOS(Id)
);
GO


CREATE TABLE COMPRAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdProveedor INT NOT NULL,
    IdUsuario INT NOT NULL,           
    Fecha DATETIME NOT NULL DEFAULT GETDATE(),
    Observaciones NVARCHAR(500),

    Cancelada BIT NOT NULL DEFAULT 0,
    MotivoCancelacion NVARCHAR(500) NULL,
    FechaCancelacion DATETIME NULL,
    IdUsuarioCancelacion INT NULL,

    FOREIGN KEY (IdProveedor) REFERENCES PROVEEDORES(Id),
    FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(Id),
    FOREIGN KEY (IdUsuarioCancelacion) REFERENCES USUARIOS(Id)
);
GO

CREATE TABLE COMPRA_LINEAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdCompra INT NOT NULL,
    IdProducto INT NOT NULL,
    Cantidad INT NOT NULL,
    PrecioUnitario DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (IdCompra) REFERENCES COMPRAS(Id),
    FOREIGN KEY (IdProducto) REFERENCES PRODUCTOS(Id)
);
GO

CREATE TABLE PRODUCTO_PROVEEDOR (
    IdProducto  INT NOT NULL,
    IdProveedor INT NOT NULL,
    CONSTRAINT PK_PRODUCTO_PROVEEDOR PRIMARY KEY (IdProducto, IdProveedor),
    CONSTRAINT FK_PP_PRODUCTO  FOREIGN KEY (IdProducto)  REFERENCES PRODUCTOS(Id),
    CONSTRAINT FK_PP_PROVEEDOR FOREIGN KEY (IdProveedor) REFERENCES PROVEEDORES(Id)
);
GO
